# Generated by Django 5.2 on 2025-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_activity_averagehr_activity_calories_activity_maxhr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
